# Site title (shown in header and browser tab)
title: NAOKI HAYASHI 

# Make local preview match GitHub Pages exactly
baseurl: "/test"

# Pages to show in the top navigation
header_pages:
  - docs/projects.md
  - docs/about.md
  - docs/lab.md

# Jekyll theme
theme: minima

# Markdown engine
markdown: kramdown

# Markdown + syntax highlighting settings
kramdown:
  input: GFM            # GitHub Flavored Markdown
  syntax_highlighter: rouge  # Code highlighting engine
